### PR TITLE
Remove stop kwarg and use write_then_readinto.

### PR DESCRIPTION
**Pull request by tannewt**
See https://github.com/adafruit/circuitpython/issues/2082 for details.

### CODE REVIEW

**Review by jerryneedell — APPROVED** [review]
@kattni  Tested on metro_m4_airlift_lite with CP5.0 alpha
No issues

**Comment by ladyada** [comment]
@jerryneedell heya i was just tring this on 2 circuitpy boards and both couldn't find the sensor due to an ID register mismatch - do you mind testing the latest release again?

**Comment by jerryneedell** [comment]
Sure, but may not be until tomorrow.

**Comment by ladyada** [comment]
no rush, just noticed it - and figured since ya tested last maybe you had insight!

**Comment by jerryneedell** [comment]
just ran the "simpletest" on a grand_central - no problem 
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-alpha.4-72-g7f1bc48a8 on 2019-09-20; Adafruit Grand Central M4 Express with samd51p20
>>> 
>>> import adt7410_simpletest
0.0
21.8047
21.7969
21.7969
21.8125
21.75
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adt7410_simpletest.py", line 11, in <module>
  File "adafruit_adt7410.py", line 91, in temperature
KeyboardInterrupt: 
>>> 
```
 Was that failing for you? any particular board you want me to try>

**Comment by ladyada** [comment]
i was using the featherwing - so odd!

**Comment by jerryneedell** [comment]
me too

**Comment by ladyada** [comment]
ok well - was probably omething with me :)

**Comment by jerryneedell** [comment]
More likely a "singe event upset" ;-)
FYI -- I also tried it on a Pyportal - no issues

**Pull request merged**
