### PR TITLE
updating lib

### PR DESCRIPTION
**Pull request by jposada202020**
Completely rewrite the library to use register, and add more examples and operation_mode function. Finally, improved the documentation.

Tested in an old Adafruit ADT7410. (Without the Stemma QT connector)

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I've got hardware coming to try this out.

**Comment by jposada202020** [comment]
YAY :). Thank you!

**Review by FoamyGuy — CHANGES_REQUESTED** [review]
Thanks for these improvements @jposada202020!

I tested this version successfully with a Feather ESP32S2-TFT. 

I am in favor of two changes:

1. I think we should implement a `high_resolution` property and setter to go along with it that allow the old API to work the same way it used to `adt.high_resolution = True` or `adt.high_resolution = False` will server has convenience properties for the new resolution_mode setter.

If we don't adopt this then we will need to change the simpletest script as well as existing code in the learn guide for the product and a handful of other learn projects that use this sensor.

I tested an implementation of this successfully:
```
    @property
    def high_resolution(self) -> bool:
        return self.resolution_mode == "HIGH_RESOLUTION"

    @high_resolution.setter
    def high_resolution(self, new_val: bool):

        if new_val:
            self.resolution_mode = HIGH_RESOLUTION
        else:
            self.resolution_mode = LOW_RESOLUTION
```

2. I think in general when there are getter and setter properties for a value it should be possible to pass the value from the getter back into the setter and have it be valid input. As it is now there are a few properties in this class that return strings like `"HIGH_RESOLUTION"` but have accompanying setters that are expecting constant values int like `adafruit_adt7410.HIGH_RESOLUTION`. I believe that the same values provided by the getter should be valid for the setter, so we could either:

- change the setter to accept strings such as `"HIGH_RESOLUTION"` which are returned by the getters. Or
- change the getters to return the constants like `adafruit_adt7410.HIGH_RESOLUTION` instead of their string counterparts. 

I can see a good case for both ways, but I think I'd lean toward having the setters accept strings since the strings are more helpful when they get printed out to the serial console with no additional logic.

**Review by FoamyGuy — APPROVED** [review]
I implemented the requested changes with the latest commit and re-tested this with a sensor and a Feather ESP32-S2 TFT

Current version looks good to me. 

Thanks again for the re-write @jposada202020!

**Pull request merged**
